### PR TITLE
Add support for building projects with SBT and Maven

### PR DESCRIPTION
**Pull request by rtfpessoa**
@PCManticore @machadoit just moved the builders to this project.

### CODE REVIEW

**Comment by PCManticore** [comment]
Cool, thanks! Just curious: it's just a move or you modified any code?

**Comment by rtfpessoa** [comment]
I did one fix. I am doing 2 different commits at the moment.

**Comment by machadoit** [comment]
Yeah it makes sense here, merge when you split into 2 commits

**Comment by rtfpessoa** [comment]
@PCManticore just commited. If there was no `scala-` directory it would create a weird path.

fyi, regarding paths, you should concatenate them with Paths or File apis.

```
import java.nio.file.Paths
val basePath = Paths.get("/tmp/my/path")
basePath.resolve("mySubDir") // /tmp/my/path/mySubDir

import java.io.File
new File("/tmp/my/path") // /tmp/my/path
new File("/tmp/my/path", "mySubDir") // /tmp/my/path/mySubDir
```

**Comment by machadoit** [comment]
:+1:

**Pull request merged**
